platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'APP' do
  # # Pods for APP
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # appcenter
  # pod 'appcenter', :path => '../node_modules/appcenter'
  # pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'
  # pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'
  # pod 'AppCenter/Crashes', '~> 2.2.0'
  # pod 'AppCenter/Analytics', '~> 2.2.0'
  # pod 'AppCenterReactNativeShared', '~> 2.2.0'

  #firebase
  pod 'Firebase', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'GoogleSignIn'

  #fbsdk
  pod 'FBSDKCoreKit', '~> 5.4.0'
  pod 'FBSDKLoginKit', '~> 5.4.0'
  pod 'FBSDKShareKit', '~> 5.4.0'
  pod 'AccountKit', '~> 5.0.1'
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

  #   # this is very important to have!
  #   rn_path = '../node_modules/react-native'
  #   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  #   pod 'React', path: rn_path, subspecs: [
   
  # 'Core',
  #   # 'RCTActionSheet',
  #   'RCTAnimation', 
  #   'RCTGeolocation',
  #   'RCTImage',
  #   'RCTLinkingIOS',
  #   'RCTNetwork',
  #   'RCTSettings',
  #   'RCTText',
  #   'RCTVibration',
  #   'RCTWebSocket'
  #   ]

  # react-native-maps
  rn_maps_path = '../node_modules/react-native-maps'  
  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  #for google place
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'


  #select image crop
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  pod 'react-native-sms', :path => '../node_modules/react-native-sms'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'


  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'


  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'



  use_native_modules!
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "mainam-react-native-payoo"
      target.remove_from_project
    end
  end
end
