# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'APP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APP
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Google/SignIn'
  
  pod 'Bolts'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'
  # facebook account kit
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
 
'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]
  
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


  rn_maps_path = '../node_modules/react-native-maps'
#   # React Native third party dependencies podspecs
#   pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
#   pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
#   # If you are using React Native <0.54, you will get the following error:
#   # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
#   # Use the following line instead:
#   #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
#   pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  #for google place
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  
  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  
  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
